# Generated by Django 4.0.3 on 2022-04-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='AddFood',
        ),
    ]
